import type { SkillPackageManifest } from '@agentclaw/shared';

/**
 * Catalog of all skills known to AgentClaw.
 *
 * Built-in skills (18) ship with the product and need no extra API keys.
 * Installable skills (6) require one or more integration credentials.
 */
export const SKILL_CATALOG: SkillPackageManifest[] = [
  // ── GTM (4 built-in) ──────────────────────────────────────────────────────
  {
    name: 'pipeline-digest',
    version: '1.0.0',
    description: 'Weekly digest of deals by stage, health indicator, and forecast roll-up.',
    agentAffinity: ['gtm-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'gtm',
    builtIn: true,
  },
  {
    name: 'weekly-digest',
    version: '1.0.0',
    description: 'GTM weekly summary: pipeline movement, new leads, and blocked deals.',
    agentAffinity: ['gtm-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'gtm',
    builtIn: true,
  },
  {
    name: 'positioning',
    version: '1.0.0',
    description: 'Generate or refresh product positioning statement with ICP and differentiation.',
    agentAffinity: ['gtm-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'gtm',
    builtIn: true,
  },
  {
    name: 'battlecard',
    version: '1.0.0',
    description: 'Competitive battlecard: strengths, weaknesses, and objection handlers.',
    agentAffinity: ['gtm-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'gtm',
    builtIn: true,
  },
  {
    name: 'launch-plan',
    version: '1.0.0',
    description: 'Product launch plan with milestones, channels, and success metrics.',
    agentAffinity: ['gtm-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'gtm',
    builtIn: true,
  },
  {
    name: 'icp',
    version: '1.0.0',
    description: 'Ideal customer profile: firmographics, pain points, and buying signals.',
    agentAffinity: ['gtm-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'gtm',
    builtIn: true,
  },
  {
    name: 'cold-email',
    version: '1.0.0',
    description: 'Cold outbound email sequence (3-touch) for a given segment.',
    agentAffinity: ['gtm-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'gtm',
    builtIn: true,
  },
  // ── Hiring (5 built-in) ───────────────────────────────────────────────────
  {
    name: 'jd',
    version: '1.0.0',
    description: 'Job description with market-based comp range and must-have criteria.',
    agentAffinity: ['hiring-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'hiring',
    builtIn: true,
  },
  {
    name: 'interview-plan',
    version: '1.0.0',
    description: '4-stage interview plan with structured questions and interviewers.',
    agentAffinity: ['hiring-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'hiring',
    builtIn: true,
  },
  {
    name: 'scorecard',
    version: '1.0.0',
    description: 'Evaluation rubric with 1–5 competency ratings and hire/no-hire guidance.',
    agentAffinity: ['hiring-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'hiring',
    builtIn: true,
  },
  {
    name: 'offer-letter',
    version: '1.0.0',
    description: 'Formal offer letter with equity/vesting terms and hire gate.',
    agentAffinity: ['hiring-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'hiring',
    builtIn: true,
  },
  {
    name: 'pipeline-review',
    version: '1.0.0',
    description: 'Weekly candidate movement report with stage blockers and action items.',
    agentAffinity: ['hiring-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'hiring',
    builtIn: true,
  },
  // ── Operations (4 built-in) ───────────────────────────────────────────────
  {
    name: 'ops-audit',
    version: '1.0.0',
    description: 'Monthly vendor spend audit with waste opportunities and recommendations.',
    agentAffinity: ['operations-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'ops',
    builtIn: true,
  },
  {
    name: 'budget-forecast',
    version: '1.0.0',
    description: '12-month cash runway projection under base, conservative, and aggressive scenarios.',
    agentAffinity: ['operations-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'ops',
    builtIn: true,
  },
  {
    name: 'vendor-review',
    version: '1.0.0',
    description: 'Vendor evaluation with competitive alternatives, ROI, and spend gate.',
    agentAffinity: ['operations-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'ops',
    builtIn: true,
  },
  {
    name: 'metric-dashboard',
    version: '1.0.0',
    description: 'Weekly KPI dashboard: burn, runway, LTV:CAC, churn rate, and headcount.',
    agentAffinity: ['operations-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'ops',
    builtIn: true,
  },
  // ── Customer Success (4 built-in) ─────────────────────────────────────────
  {
    name: 'health-score',
    version: '1.0.0',
    description: 'Customer health score (0–100) with red/yellow/green status and trend.',
    agentAffinity: ['customer-success-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'cs',
    builtIn: true,
  },
  {
    name: 'qbr-prep',
    version: '1.0.0',
    description: 'QBR agenda with ROI analysis, expansion opportunities, and renewal strategy.',
    agentAffinity: ['customer-success-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'cs',
    builtIn: true,
  },
  {
    name: 'churn-analysis',
    version: '1.0.0',
    description: '5-whys churn root-cause analysis with prevention recommendations.',
    agentAffinity: ['customer-success-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'cs',
    builtIn: true,
  },
  {
    name: 'playbook-builder',
    version: '1.0.0',
    description: 'Repeatable CS workflows for onboarding, expansion, renewal, and recovery.',
    agentAffinity: ['customer-success-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'cs',
    builtIn: true,
  },
  // ── Founder / Meta (4 built-in) ───────────────────────────────────────────
  {
    name: 'heartbeat-orchestrator',
    version: '1.0.0',
    description: 'Daily 5-min digest pulling summaries from all 4 specialist agents.',
    agentAffinity: ['founder-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'founder',
    builtIn: true,
  },
  {
    name: 'daily-standup',
    version: '1.0.0',
    description: 'Structured standup format: wins, status, blockers, and top-3 actions.',
    agentAffinity: ['founder-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'founder',
    builtIn: true,
  },
  {
    name: 'decision-router',
    version: '1.0.0',
    description: 'Routes any founder question to the right specialist agents and synthesises answers.',
    agentAffinity: ['founder-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'founder',
    builtIn: true,
  },
  {
    name: 'board-prep',
    version: '1.0.0',
    description: 'Quarterly board deck: 12 slides covering metrics, progress, forecast, and asks.',
    agentAffinity: ['founder-agent'],
    requiredIntegrations: [],
    requiredSecrets: [],
    category: 'founder',
    builtIn: true,
  },

  // ── Installable skills (6) — require external integration credentials ──────
  {
    name: 'notion-okr-sync',
    version: '1.0.0',
    description: 'Syncs OKR progress to a Notion database and writes structured update notes.',
    author: 'AgentClaw',
    agentAffinity: ['founder-agent', 'operations-agent'],
    requiredIntegrations: ['notion'],
    requiredSecrets: ['NOTION_API_KEY', 'NOTION_OKR_DATABASE_ID'],
    category: 'ops',
    builtIn: false,
  },
  {
    name: 'brex-spend-report',
    version: '1.0.0',
    description: 'Pulls real-time Brex card spend and surfaces budget variance against plan.',
    author: 'AgentClaw',
    agentAffinity: ['operations-agent'],
    requiredIntegrations: ['brex'],
    requiredSecrets: ['BREX_API_TOKEN'],
    category: 'finance',
    builtIn: false,
  },
  {
    name: 'calendly-deal-velocity',
    version: '1.0.0',
    description: 'Tracks demo-to-close velocity from Calendly meeting data for GTM insights.',
    author: 'AgentClaw',
    agentAffinity: ['gtm-agent'],
    requiredIntegrations: ['calendly'],
    requiredSecrets: ['CALENDLY_API_TOKEN'],
    category: 'gtm',
    builtIn: false,
  },
  {
    name: 'slack-pulse',
    version: '1.0.0',
    description: 'Daily team sentiment and activity pulse via Slack channel analytics.',
    author: 'AgentClaw',
    agentAffinity: ['founder-agent'],
    requiredIntegrations: ['slack-ops'],
    requiredSecrets: ['SLACK_USER_TOKEN'],
    category: 'ops',
    builtIn: false,
  },
  {
    name: 'brex-budget-alert',
    version: '1.0.0',
    description: 'Fires a spend gate when any Brex budget is within 20% of its monthly limit.',
    author: 'AgentClaw',
    agentAffinity: ['operations-agent'],
    requiredIntegrations: ['brex'],
    requiredSecrets: ['BREX_API_TOKEN'],
    category: 'finance',
    builtIn: false,
  },
  {
    name: 'notion-hiring-tracker',
    version: '1.0.0',
    description: 'Mirrors the hiring pipeline to a Notion database with stage and status columns.',
    author: 'AgentClaw',
    agentAffinity: ['hiring-agent'],
    requiredIntegrations: ['notion'],
    requiredSecrets: ['NOTION_API_KEY', 'NOTION_HIRING_DATABASE_ID'],
    category: 'hiring',
    builtIn: false,
  },
];
